substitutions:
  board_type: "esp32doit-devkit-v1"
  board_framework: "arduino"
  device_name: "workshop"
  device_desc: "Temp Humidity Sensor"
  device_area: "Workshop"
  humidity_target_initial: "60"
  max_daily_stepdown_initial: "0.5"
  display_address: "0x27"
  display_dimensions: "16x2"

esphome:
  name: $device_name
  comment: Temp Humidity Sensor
  friendly_name: $device_name
  area: $device_area
  on_boot:
    - ds1307.read_time
    - logger.log:
        level: DEBUG
        format: 'Humidity target is set to %d'
        args: ['id(humidity_target)']
    - logger.log:
        level: DEBUG
        format: 'Max Daily step-down is set to %d'
        args: ['id(max_daily_stepdown)']
    - logger.log:
        level: DEBUG
        format: 'Dry Programme Activation is set to %d'
        args: ['id(dry_prog_active)']

esp32:
  board: $board_type
  framework:
    type: $board_framework

logger:

api:
  encryption:
    key: !secret ha_api_key

ota:
  - platform: esphome
    password: !secret ota_flash_pass

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pw
  ap:
    ssid: ESPhome Fallback Hotspot
    password: !secret wifi_fallback_pw

captive_portal:

i2c:
  frequency: 400kHz

output:
  - platform: ledc
    pin: GPIO04
    id: fan_control
    frequency: 25000 Hz
    min_power: 0%
    max_power: 100%

fan:
  - platform: speed
    output: fan_control
    name: "Dehumidifier"
    id: dehumid_fan
    restore_mode: ALWAYS_OFF
    on_turn_on:
    - switch.turn_on: dehumid_relay
    on_turn_off:
    - switch.turn_off: dehumid_relay

time:
  - platform: ds1307
    id: ds1307_time
    update_interval: never
  - platform: homeassistant
    on_time_sync:
      then:
        ds1307.write_time:

web_server:
  port: 80
  version: 3

sensor:

  - platform: wifi_signal
    name: WiFi Strength
    update_interval: 60s

  - platform: sht4x
    temperature:
      name: "Temperature"
      id: "sht_temp"
    humidity:
      name: "Humidity"
      id: "sht_humidity"
      on_value:
        then:
          - script.execute: dehumidifier_action
    update_interval: 60s

  - platform: homeassistant
    name: "Humidity Target"
    entity_id: input_number.sht45_humidity_target
    id: sht45_humidity_target
    unit_of_measurement: "%"
    device_class: "humidity"
    internal: true
    accuracy_decimals: 1
    on_value:
      then:
        if:
          condition: 
            lambda: 'return id(humidity_target) != int(x);'
          then:
            - logger.log:
                level: DEBUG
                format: 'Humidity target changed from %d to %d'
                args: ['id(humidity_target)', 'int(x)']
            - globals.set:
                id: humidity_target
                value: !lambda 'return int(x);'
            - script.execute: dehumidifier_action

  - platform: homeassistant
    name: "Max Daily Step-Down (Humidity)"
    entity_id: input_number.sht45_max_daily_stepdown
    id: sht45_max_daily_stepdown
    unit_of_measurement: "%"
    device_class: "humidity"
    internal: false
    accuracy_decimals: 1
    on_value:
      then:
        if:
          condition: 
            lambda: 'return id(max_daily_stepdown) != float(x);'
          then:
            - logger.log:
                level: DEBUG
                format: 'Max Daily Step-Down (Humidity) changed from %f to %f'
                args: ['id(max_daily_stepdown)', 'float(x)']
            - globals.set:
                id: max_daily_stepdown
                value: !lambda 'return float(x);'

  - platform: pulse_counter
    pin:
      number: GPIO23
    name: Dehumidifier Fan Speed (RPM)
    id: fan_pulse
    unit_of_measurement: 'RPM'
    filters:
      - multiply: 0.5
    count_mode:
      rising_edge: INCREMENT
      falling_edge: DISABLE
    update_interval: 30s

switch:
  - platform: gpio
    pin: 
      number: GPIO18
    name: "Dehumidifier Relay"
    id: dehumid_relay
    device_class: switch
    restore_mode: RESTORE_DEFAULT_OFF
    internal: true
    on_turn_on:
      - fan.turn_on: dehumid_fan
    on_turn_off:
      - fan.turn_off: dehumid_fan

  - platform: template
    name: "Humidity Target Status"
    id: setpoint_switch
    device_class: switch
    restore_mode: RESTORE_DEFAULT_OFF
    lambda: |-
      if (id(setpoint_active)) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
      - logger.log:
          level: DEBUG
          format: 'Set point active status ON'
      - globals.set:
          id: setpoint_active
          value: "true"
      - script.execute: dehumidifier_action
    turn_off_action:
      - logger.log:
            level: DEBUG
            format: 'Set point active status OFF'
      - globals.set:
          id: setpoint_active
          value: "false"
      - script.execute: dehumidifier_action

script:
  id: dehumidifier_action
  then:
    - if:
        condition:
          lambda: 'return (int(id(sht_humidity).state) > id(humidity_target) && id(setpoint_active));'
        then:
          - logger.log: 
              format: 'The humidity (%d) is above the target humidity (%d). Switching dehumidifier on.'
              args: ['int(id(sht_humidity).state)', 'id(humidity_target)']
          - switch.turn_on: dehumid_relay
          - delay: 30s
        else:
          - logger.log:
              format: 'The humidity (%d) is under the target (%d) or the humidity target is not activated. Switching dehumidifier off.'
              args: ['int(id(sht_humidity).state)', 'id(humidity_target)']
          - switch.turn_off: dehumid_relay

globals:
  - id: humidity_target
    type: int
    restore_value: true
    initial_value: $humidity_target_initial
  - id: max_daily_stepdown
    type: float
    restore_value: true
    initial_value: $max_daily_stepdown_initial
  - id: dry_prog_active
    type: bool
    restore_value: true
    initial_value: "false"
  - id: dry_prog_start
    type: time_t
    restore_value: true
    initial_value: ""
  - id: setpoint_active
    type: bool
    restore_value: true
    initial_value: "false"
  - id: dehumid_suspend
    type: bool
    restore_value: true
    initial_value: "false"