esphome:
  name: workshop
  comment: Temp Humidity Sensor
  area: Workshop
  on_boot:
    - logger.log:
        level: DEBUG
        format: 'Humidity threshold is set to %d'
        args: ['id(humidity_threshold)']
    - logger.log:
        level: DEBUG
        format: 'Humidity target is set to %d'
        args: ['id(humidity_target)']
    - logger.log:
        level: DEBUG
        format: 'Max Daily step-down is set to %d'
        args: ['id(max_daily_stepdown)']
    - logger.log:
        level: DEBUG
        format: 'Dry Programme Activation is set to %d'
        args: ['id(dry_prog_active)']

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: arduino

logger:

api:
  encryption:
    key: !secret ha_api_key

ota:
  - platform: esphome
    password: !secret ota_flash_pass

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pw
  ap:
    ssid: "ESPhome Fallback Hotspot"
    password: !secret wifi_fallback_pw

captive_portal:

i2c:
  frequency: 400kHz

sensor:
  - platform: sht4x
    temperature:
      name: "Temperature"
      id: "sht_temp"
    humidity:
      name: "Humidity"
      id: "sht_humidity"
      on_value:
        then:
          - if:
              condition:
                lambda: 'return int(id(sht_humidity).state) > id(humidity_threshold);'
              then:
                - logger.log: 
                    format: 'The humidity (%d) is over the threshold (%d). Switching dehumidifier on.'
                    args: ['int(id(sht_humidity).state)', 'id(humidity_threshold)']
                - switch.turn_on: relay_status
                - delay: 30s
              else:
                - logger.log:
                    format: 'The humidity (%d) is under the threshold (%d). Switching dehumidifier off.'
                    args: ['int(id(sht_humidity).state)', 'id(humidity_threshold)']
                - switch.turn_off: relay_status
    update_interval: 60s

  - platform: homeassistant
    name: "Humidity Threshold - Upper"
    entity_id: input_number.sht45_humidity_threshold
    id: sht45_humidity_threshold
    unit_of_measurement: "%"
    device_class: "humidity"
    internal: false
    accuracy_decimals: 1
    on_value:
      then:
        if:
          condition: 
            lambda: 'return id(humidity_threshold) != int(x);'
          then:
            - logger.log:
                level: DEBUG
                format: 'Humidity threshold changed from %d to %d'
                args: ['id(humidity_threshold)', 'int(x)']
            - globals.set:
                id: humidity_threshold
                value: !lambda 'return int(x);'

  - platform: homeassistant
    name: "Humidity Target"
    entity_id: input_number.sht45_humidity_target
    id: sht45_humidity_target
    unit_of_measurement: "%"
    device_class: "humidity"
    internal: false
    accuracy_decimals: 1
    on_value:
      then:
        if:
          condition: 
            lambda: 'return id(humidity_target) != int(x);'
          then:
            - logger.log:
                level: DEBUG
                format: 'Humidity target changed from %d to %d'
                args: ['id(humidity_target)', 'int(x)']
            - globals.set:
                id: humidity_target
                value: !lambda 'return int(x);'

  - platform: homeassistant
    name: "Max Daily Step-Down (Humidity)"
    entity_id: input_number.sht45_max_daily_stepdown
    id: sht45_max_daily_stepdown
    unit_of_measurement: "%"
    device_class: "humidity"
    internal: false
    accuracy_decimals: 1
    on_value:
      then:
        if:
          condition: 
            lambda: 'return id(max_daily_stepdown) != float(x);'
          then:
            - logger.log:
                level: DEBUG
                format: 'Max Daily Step-Down (Humidity) changed from %f to %f'
                args: ['id(max_daily_stepdown)', 'float(x)']
            - globals.set:
                id: max_daily_stepdown
                value: !lambda 'return float(x);'

switch:
  - platform: gpio
    pin: 
      number: GPIO18
    name: "12v Relay Status"
    id: relay_status
    device_class: switch
    restore_mode: RESTORE_DEFAULT_OFF

display:
  - platform: lcd_pcf8574
    dimensions: 16x2
    address: 0x27
    lambda: |-
      it.printf(0, 0, "T: %2.1fC", id(sht_temp).state);
      it.printf(0, 1, "H: %2.1f%% > %2.1f%%", id(sht_humidity).state, id(sht45_humidity_target).state);

time:
  - platform: homeassistant
    id: homeassistant_time

web_server:
  port: 80
  version: 3

globals:
  - id: humidity_threshold
    type: int
    restore_value: true
    initial_value: '65'
  - id: humidity_target
    type: int
    restore_value: true
    initial_value: '60'
  - id: max_daily_stepdown
    type: float
    restore_value: true
    initial_value: '0.5'
  - id: dry_prog_active
    type: bool
    restore_value: true
    initial_value: "false"
  - id: dry_prog_start
    type: time_t
    restore_value: true
    initial_value: ""
  - id: dehumid_suspend
    type: bool
    restore_value: true
    initial_value: "false"